CREATE TABLE NEWS (
    ID VARCHAR(50) PRIMARY KEY,
    AUTHOR VARCHAR(50),
    AUTHOR_FULL_NAME VARCHAR(100),
    TITLE VARCHAR(500),
    DOWNS INT,
    UPS INT,
    SCORE INT,
    THUMBNAIL VARCHAR(200),
    EDITED BOOLEAN,
    OVER_18 BOOLEAN,
    NUM_COMMENTS INT,
    URL VARCHAR(200),
    CREATED TIMESTAMP,
    IS_VIDEO BOOLEAN
);