spring:
  main:
    web-application-type: NONE


reddit:
  url: https://www.reddit.com
  user-agent: ${os.name}:org.ghilardi.newsreader:1.0.0 (by /u/dghila)

news-format:
  header: "Today I Learned:"
  row-template: "* {{title}} - {{thumbnail}}"